### ISSUE TITLE
Unwanted large number conversion

### ISSUE THREAD

**Issue by thim81** [stoplightio/yaml#53]
## Describe the bug

Large number ranges gets unwanted converted or rounded, like for example

```yaml
components:
  schemas:
    Pet:
        NumberLimitsSchema:
          type: number
          maximum: 9999999999999.99999
          minimum: 0
          multipleOf: 0.0000000001
```

After parsing the YAML, the output becomes:

```yaml
components:
  schemas:
    Pet:
        NumberLimitsSchema:
          type: number
          maximum: 10000000000000
          minimum: 0
          multipleOf: 1e-1
```

## To Reproduce

1. Given OpenAPI YAML snippet
2. Convert the YAML file using `const sy = require('@stoplight/yaml'); input = sy.parse(fs.readFileSync(inputFilename, 'utf8'))`
3. See result

## Expected behaviour

```yaml
components:
  schemas:
    Pet:
        NumberLimitsSchema:
          type: number
          maximum: 9999999999999.99999
          minimum: 0
          multipleOf: 0.0000000001
```

## Additional context

**Environment (remove any that are not applicable):**
 - Library version: 4.2.2
 - OS: Ubuntu/Mac
 - Platform: NodeJS 17
